v0.2 cmds from textfile

diff --git a/scripts/refresh_panes_v0 b/scripts/refresh_panes_v0
--- a/scripts/refresh_panes_v0
+++ b/scripts/refresh_panes_v0
@@ -7,18 +7,97 @@
 # USAGE:            ./main_v3.sh
 # DEPENDENCIES:     No dependencies
 # LICENSE:          MIT License
-# VERSION:          0.1.0
+# VERSION:          0.2.0
 #====================================================
 
-# Refresh panes with the given arguments
+
+#argument_value_1="$1"
+
+FILE_NAME="user_arguments_v0.txt"
+
+if [ ! -f "$FILE_NAME" ]; then
+    echo "Error: $FILE_NAME not found!"
+    exit 1
+fi
+
+# Read commands from the file
+cmd1=$(sed -n '1p' $FILE_NAME)
+cmd2=$(sed -n '2p' $FILE_NAME)
+cmd3=$(sed -n '3p' $FILE_NAME)
+cmd4=$(sed -n '4p' $FILE_NAME)
+
+echo "Commands: $cmd1 $cmd2 $cmd3 $cmd4"
+
+
+
+# Define display table function
+display_table() {
+
+    local cmd1="$1"
+    local cmd2="$2"
+    local cmd3="$3"
+    local cmd4="$4"
+
+    # Define column widths
+    width1=18
+    width2=18
+
+    # Format and display the table
+    table_content=$(printf "%-${width1}s | %-${width2}s\n" "$cmd1" "$cmd2"
+                  printf "+%s+%s+\n" "$(printf '%*s' "$width1" | tr ' ' '-')" "$(printf '%*s' "$width2" | tr ' ' '-')"
+                  printf "%-${width1}s | %-${width2}s\n" "$cmd3" "$cmd4")
+
+    echo "$table_content"
+
+}
+
+
+# Temporary leaving table field empty.
+
+# Sent a command to each pane
+tmux send-key -t 0 './tmux_panes_display_cmds_v1.sh menu_info' C-m
+
+
+tmux send-key -t 3 "$(cat << EOF 
+$(declare -f display_table) 
+$(table_content=$(display_table "$cmd1" "$cmd2" "$cmd3" "$cmd4"))
+EOF
+)" C-m
+
+
+#tmpfile=$(mktemp)
+#cat << EOF > "$tmpfile"
+#$(declare -f display_table)
+#
+#display_table
+#EOF
+#
+#tmux send-key -t 3 "$(cat "$tmpfile")" C-m
+ 
+#tmux send-key -t 3 "echo 'just sth'" C-m
+#rm "$tmpfile"
+
+
+
+# Refresh panes with the given commands or arguments
 
 while true; do
-    
-    tmux send-key -t 1 "./tmux_panes_display_cmds_v2.sh $1" C-m
-    tmux send-key -t 1 "date" C-m
-    tmux send-key -t 4 "./tmux_panes_display_cmds_v2.sh $2" C-m
+    # date is used to check update every 5 seconds
 
-    tmux send-key -t 2 "./tmux_panes_display_cmds_v2.sh $3" C-m
-    tmux send-key -t 5 "./tmux_panes_display_cmds_v2.sh $4" C-m
+    tmux send-key -t 1 "./tmux_panes_display_cmds_v2.sh $cmd1" C-m
+    tmux send-key -t 1 "date" C-m
+ 
+    tmux send-key -t 4 "./tmux_panes_display_cmds_v2.sh $cmd2" C-m
+    tmux send-key -t 4 "date" C-m
+
+    tmux send-key -t 2 "./tmux_panes_display_cmds_v2.sh $cmd3" C-m
+    tmux send-key -t 2 "date" C-m
+
+
+    tmux send-key -t 5 "./tmux_panes_display_cmds_v2.sh $cmd4" C-m
+    tmux send-key -t 5 "date" C-m
+
+
     sleep 5
 done
+
